<!DOCTYPE html>
<html>
<head>
<title>Pencarian Lyrics</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="style.css">
</head>

<body>
<div class="grid-container">
  <div class="header">
    <form method="post" align="center" >
		<input type="text" name="artist" placeholder="Artist/Band">
		<input type="text" name="lagu" placeholder="Lagu">
		<input type="submit" name="submit" value="Cari Lagu">
	</form>
  </div>
  <hr>
  <div class="left">Lyrics <hr>
  <?php
if (isset($_POST['submit'])){
$artist = $_POST['artist'];
$lagu = $_POST['lagu'];
$newartist = str_replace(' ', '%20', $artist);
$newlagu = str_replace(' ', '%20', $lagu);

$curl = curl_init();

curl_setopt_array($curl, [
	CURLOPT_URL => "https://lyrics-finder1.p.rapidapi.com/".$newartist."/".$newlagu,
	CURLOPT_RETURNTRANSFER => true,
	CURLOPT_FOLLOWLOCATION => true,
	CURLOPT_ENCODING => "",
	CURLOPT_MAXREDIRS => 10,
	CURLOPT_TIMEOUT => 30,
	CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
	CURLOPT_CUSTOMREQUEST => "GET",
	CURLOPT_HTTPHEADER => [
		"X-RapidAPI-Host: lyrics-finder1.p.rapidapi.com",
		"X-RapidAPI-Key: 5391a8889emsh9897a2f8331e189p1b7085jsn808a8981f1cc"
	],
]);

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
	echo "cURL Error #:" . $err;
} else {
	echo $response;
}
}
?>
  </div>
  <div class="right">Youtube <hr>
  <?php
function searchYoutube($q){
	$q=urlencode($q);// url encodekan
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://www.googleapis.com/youtube/v3/search'.
								  '?part=snippet&maxResults=10'.
								  '&q='.$q.
								  '&key=AIzaSyAPv4GAMBqodPjbNNrWl1g7cJbGrVipqmg');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

	curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

	$headers = array();
	$headers[] = 'Accept: application/json';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch); // format json
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	return json_decode($result,true);// returnkan dalam bentuk array assosiatif
}
?>

<?php
if (isset($_POST['submit']) )
{
$lagu=$_POST['lagu'];
if (empty($lagu))
        {
            $response = array(
                  "type" => "error",
                  "message" => "Please enter the keyword."
                );
        } 
    }
$response=searchYoutube($lagu);
?>

<?php
$listVideo=$response["items"];// ambil field items dari $response
foreach($listVideo as $video){
	echo "<div>";
	echo "<h5>".$video["snippet"]["title"]."</h5>";
	if($video["id"]["kind"]=="youtube#video")
		echo "<a href=\"https://www.youtube.com/watch?v=".$video["id"]["videoId"]."\">";
	else
	if($video["id"]["kind"]=="youtube#channel")
		echo "<a href=\"https://www.youtube.com/channel/".$video["id"]["channelId"]."\">";
	echo "<img src=\"".$video["snippet"]["thumbnails"]["default"]["url"]."\">";
	echo "</a>";
	echo "</div>";
}
?>

  </div>  
 
  <div class="footer">
	<p>Footer</p>
	</div>
  </div>
</body>

